# -*- coding: utf-8 -*-
"""djangoapp.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1kYy-MLc0TklvEWQguRfZRJ5hHx2haIC8
"""

from django.db import models
from django.shortcuts import render
from .models import ServiceRequest
class ServiceRequest(models.Model):
    SERVICE_TYPES = (
        ('gas_leak', 'Gas Leak'),
        ('meter_issue', 'Meter Issue'),

    )

    customer_name = models.CharField(max_length=100)
    service_type = models.CharField(choices=SERVICE_TYPES, max_length=20)
    details = models.TextField()
    attachment = models.FileField(upload_to='service_attachments/', blank=True, null=True)
    submitted_at = models.DateTimeField(auto_now_add=True)
    resolved_at = models.DateTimeField(blank=True, null=True)
    status = models.CharField(max_length=20, default='pending')

    def __str__(self):
        return f"Service Request #{self.id} - {self.service_type}"



def submit_service_request(request):
    if request.method == 'POST':

    return render(request, 'submit_service_request.html')

def track_request_status(request, request_id):

    return render(request, 'track_request_status.html', {'service_request': service_request})

def manage_requests(request):

    return render(request, 'manage_requests.html', {'service_requests': service_requests})


from django.urls import path
from . import views
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('submit/', views.submit_service_request, name='submit_service_request'),
    path('track/<int:request_id>/', views.track_request_status, name='track_request_status'),
    path('manage/', views.manage_requests, name='manage_requests'),
]

urlpatterns = [
    path('admin/', admin.site.urls),
    path('service/', include('gas_utility_app.urls')),
]

from django.contrib import admin
from .models import ServiceRequest

admin.site.register(ServiceRequest)